#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
cd ${OPENSHIFT_REPO_DIR}

.openshift/action_hooks/stop

#tell play to save log files in openshift log dir
export PLAY_LOG_PATH=${OPENSHIFT_DIY_LOG_DIR}
export _JAVA_OPTIONS="-Xms256M -Xmx512M"

#run with openshift id
${OPENSHIFT_DATA_DIR}play-2.2.1/play -Dhttp.port=${OPENSHIFT_DIY_PORT} -Dhttp.address=${OPENSHIFT_DIY_IP} run
