#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

# The logic to stop your application should be put in this script.
cd ${OPENSHIFT_REPO_DIR}

if [[ -f "RUNNING_PID" ]]; then
  ${OPENSHIFT_DATA_DIR}play-2.2.1/play stop
fi
